<template>
  <main class="mx-auto max-w-7xl px-4 py-6">
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><span class="tag bg-blue-50 text-blue-700">{{session?.phase_label||'初始化中'}}</span><h1 class="mt-2 text-2xl font-bold">{{session?.job_title||'模拟面试'}}</h1><p class="text-sm text-slate-500">{{session?.company||'目标岗位'}} · 第 {{session?.current_round||0}}/{{session?.max_rounds||10}} 轮</p></div><div class="text-right"><span :class="session?.degraded_mode?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'" class="tag">{{session?.degraded_mode?'规则降级':'Agent 运行中'}}</span><div class="mt-2 h-2 w-40 rounded-full bg-slate-200"><div class="h-2 rounded-full bg-blue-600" :style="{width:`${Math.min((session?.current_round||0)/(session?.max_rounds||10)*100,100)}%`}"></div></div></div></div>
    <div class="grid gap-6 lg:grid-cols-3"><section class="space-y-4 lg:col-span-2"><div v-for="turn in session?.turns" :key="turn.id" class="card p-5"><div class="flex items-center justify-between"><span class="text-sm font-medium text-blue-600">{{turn.phase_label||turn.question.category}} {{turn.is_followup?'· 追问':''}}</span><span v-if="turn.evaluation" class="tag bg-emerald-50 text-emerald-700">{{turn.evaluation.overall_score}} 分</span></div><h2 class="mt-3 text-lg font-semibold text-slate-900">{{turn.question.question}}</h2><template v-if="!turn.answer&&isCurrent(turn)"><textarea v-model="answer" class="input mt-4 h-36" placeholder="用真实经历、个人行动和结果回答"></textarea><button class="btn-primary mt-3" :disabled="running||!answer.trim()" @click="submit(turn.id)">{{running?processingLabel:'提交回答'}}</button></template><div v-if="turn.answer" class="mt-4 whitespace-pre-wrap rounded-lg bg-slate-50 p-4 text-sm">{{turn.answer}}</div><div v-if="turn.evaluation" class="mt-4 space-y-2 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm"><p><b>优势：</b>{{turn.evaluation.strengths?.join('、')}}</p><p><b>证据缺口：</b>{{turn.evaluation.evidence_gaps?.join('、')||'暂无'}}</p><p><b>改进建议：</b>{{turn.evaluation.improvement_suggestion}}</p><p v-if="turn.evaluation.factual_errors?.length"><b class="text-red-700">事实错误：</b>{{turn.evaluation.factual_errors.join('、')}}</p></div></div><p v-if="error" class="rounded-lg bg-red-50 p-3 text-sm text-red-700">{{error}}</p></section><aside class="space-y-4"><div class="card p-5"><h2 class="font-semibold">Agent 工作流</h2><div class="mt-3 space-y-2 text-sm"><p v-for="log in logs" :key="log" class="text-slate-600">✓ {{log}}</p><p v-if="running" class="text-blue-600">● {{processingLabel}}</p></div></div><div class="card p-5"><h2 class="font-semibold">公开资料来源</h2><div v-for="s in session?.sources" :key="s.id" class="mt-3"><a v-if="s.url" :href="s.url" target="_blank" class="block text-sm text-blue-600 underline">{{s.title}}</a><span v-else class="block text-sm text-slate-600">{{s.title}}</span><p v-if="s.status==='summary_only'" class="mt-1 text-xs text-amber-700">已保存搜索摘要；原网页正文未能抓取</p></div><p v-if="!session?.sources?.length" class="mt-2 text-sm text-slate-400">未采集到公开资料</p></div></aside></div>
  </main>
</template>
<script setup lang="ts">
import {getInterview,stream} from '~/utils/api'
const route=useRoute(),id=String(route.params.id),session=ref<any>(),answer=ref(''),running=ref(false),processingLabel=ref('评估中…'),error=ref(''),logs=ref<string[]>([])
function isCurrent(t:any){return !t.answer&&session.value?.turns.filter((x:any)=>!x.answer).at(-1)?.id===t.id}
async function load(){session.value=(await getInterview(id)).data}
function handle(n:string,d:any){if(n==='workflow_node_enter'){logs.value.push(`进入 ${d.node_name}`);if(d.node_name==='生成下一题或面试总评')processingLabel.value='正在生成下一题…'}if(n==='workflow_node_leave')logs.value.push(`完成 ${d.node_name}`);if(n==='question'){const x=session.value.turns.find((t:any)=>t.id===d.id);if(x)Object.assign(x,d);else session.value.turns.push(d)}if(n==='evaluation'){const x=session.value.turns.find((t:any)=>t.id===d.turn_id);if(x)x.evaluation=d.evaluation}if(n==='interview_completed'){session.value.final_review=d}}
async function begin(){running.value=true;try{await stream(`/interviews/${id}/start`,undefined,handle);await load()}catch(e:any){error.value=e.message}finally{running.value=false}}
async function submit(turnId:number){running.value=true;processingLabel.value='评估中…';error.value='';try{await stream(`/interviews/${id}/answer`,{turn_id:turnId,answer:answer.value},handle);answer.value='';await load();if(session.value.status==='completed')await navigateTo(`/interview/result/${id}`)}catch(e:any){error.value=e.message}finally{running.value=false}}
onMounted(async()=>{await load();const notice=sessionStorage.getItem(`interview-source-notice-${id}`);if(notice){logs.value.push(notice);sessionStorage.removeItem(`interview-source-notice-${id}`)}if(!session.value.turns.length)await begin()})
</script>
